# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

brews:
  - name: pug
    homepage: https://github.com/leg100/pug
    description: "Terminal user interface for terraform power users."
    folder: Formula
    commit_author:
      name: "Louis Garman"
      email: "louisgarman@gmail.com"
    repository:
      owner: leg100
      name: homebrew-tap
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/leg100/pug/internal/app.Version={{.Major}}.{{.Minor}}.{{.Patch}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{- .Arch }}"
